name: linter-check
on: [push]
jobs:
  check-with-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: make install

      - name: rubocop
        run: make lint