name: linter-check
on: [push]
jobs:
  check-with-linter:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby 3.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.x

      - name: Install dependencies
        run: make install

      - name: rubocop
        run: make lint